version: 2
jobs:
   build:
      docker:
        #アプリのバージョンを指定
        - image: circleci/ruby:2.6.3-node
          environment:
            #自身の登録しているユーザに変える。
            MYSQL_USER: user
            DB_HOST: 127.0.0.1
            RAILS_ENV: test
        - image: circleci/mysql:8.0.4
          environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_DATABASE: test_db
            MYSQL_USER: user
            MYSQL_PASSWORD: trust
      #自身のアプリ名にする
      working_directory: ~/golf_app
      steps:
        - checkout
        #bundle キャッシュをリストアする。公式の設定通り。
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "Gemfile.lock" }}
              - v1-dependencies-
        - run:
            name: install dependencies
            command: |
              gem install bundler -v 2.1.4
              bundle install --jobs=4 --retry=3 --path vendor/bundle
        # bundle キャッシュを保存する。公式の設定通り。
        - save_cache:
            key: v1-dependencies-{{ checksum "Gemfile.lock" }}
            paths:
              - ./vendor/bundle

        - run:
            name: DBの起動を待つ
            command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

        - run: bundle exec rake db:create
        - run: bundle exec rake db:schema:load

        # rspecを実行する
        - run:
            name: rspecを実行
            command: bundle exec bin/rspec
