default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: golf_app_development

test:
  <<: *default
  database: golf_app_test

production:
  <<: *default
  database: golf_app_production
  username: golf_app
  password:
