default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5
  port: 5432

development:
  <<: *default
  database: myapp_deveropment
  host: localhost
  port: 5432

test:
  <<: *default
  database: myapp_test
  host: localhost

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
